spring:
  application:
    name: elasticsearch-demo

  data:
    elasticsearch:
      client:
        endpoints: ${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}

server:
  port: 8080

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    com.example.elasticsearch: DEBUG

# Elasticsearch接続の再試行設定
management:
  health:
    elasticsearch:
      enabled: true
